### ISSUE TITLE
Recursion Error in NiceToICY

### ISSUE THREAD

**Issue by twomugs** [nagyrobi/media_player.linkplay#102]
Some of my Home Assistant integrations have been dropping out recently, and when I looked at the logs, it seem that linkplay is the cause behind it.

Here are a couple of log from HA for Waze and Hive integrations showing recursive function call to the NiceToICY function:
[hive.txt](https://github.com/nagyrobi/home-assistant-custom-components-linkplay/files/9993505/hive.txt)
[waze.txt](https://github.com/nagyrobi/home-assistant-custom-components-linkplay/files/9993506/waze.txt)

I'm running HA 2022.10.05 in docker container, with LinkPlay 3.1.8 installed through HACS.
The speaker is an AudioPro C5A

I took a look at the code and found this:
async_update_from_icecast() replaces urllib.request.http.client.HTTPResponse._read_status function with NiceToICY(), which in turn calls the original function. However, there is no test to see if this substitution has already been performed, so it end up getting wrapped again and again with each successive call to async_update_from_icecast(). Eventually the call stack becomes too deep, leads the the RecursionError exception.

This may explain some of the timeouts and other 'network problems' that have been reported for this integration.

As the urllib library is used by other integrations, it can cause problesm for other integrations at random too.

**Comment by nagyrobi** [comment]
Thanks. @marcelveldt this must be it

**Comment by Thrasher2020** [comment]
Is there a solution to this issue? It is taking down my integrations as well :(
