### ISSUE TITLE
add feature: reboot device

### ISSUE THREAD

**Issue by jahegu** [nagyrobi/media_player.linkplay#105]
Not sure if it's available for all devices but acording Arylic API documentation it is possible to force a reboot device:

GET /httpapi.asp?command=reboot

https://developer.arylic.com/httpapi/#reboot-device

is it possible to add this feature on the component?

**Comment by nagyrobi** [comment]
Reboot has been removed from the API a few years ago...

**Comment by jahegu** [comment]
Ok, 
On my case i have Ayrlic DIY board and it is still supported... And needed sometimes

BR,

**Comment by nagyrobi** [comment]
it's not a real reboot, it just kills the linkplay process in the board. The linux system behind it doesn't really reboot, just restarts the process.

**Comment by jahegu** [comment]
Thank you very much for the info. In my case it's been enough to fix online
radio streaming issues. I scheduled a daily reboot API and this device
rarely fails again.
It's also sure that I check a ping /t on the device and rarely it loses any
packet so it should, as you say, just a light service reboot.

A part of power off-on I understand that there is no better way to restart
the device?

BR,

**Comment by nagyrobi** [comment]
add a Sonoff switch in front of it...
