### ISSUE TITLE
Media over WiFi

### ISSUE THREAD

**Issue by DanielHouston** [nagyrobi/media_player.linkplay#106]
When trying to play TTS on a Arylic S50 Pro+, the following error is generated in the debug logs for the component:

`Detected integration that calls media_source.async_resolve_media without passing an entity_id. Please report issue for media_source using this method at homeassistant/components/media_source/__init__.py, line 147: report("calls media_source.async_resolve_media without passing an entity_id")`

http://deviceIP/httpapi.asp?command=getStatusEx:

`{
  "uuid": "FF31F09E74C5E074E359B693",
  "DeviceName": "XXX",
  "GroupName": "XXX",
  "ssid": "SoundSystem_AC52",
  "language": "en_us",
  "firmware": "4.6.415145",
  "hardware": "A31",
  "build": "release",
  "project": "ARYLIC_S50A",
  "priv_prj": "ARYLIC_S50A",
  "project_build_name": "a31rakoit",
  "Release": "20220427",
  "temp_uuid": "36BFEE39F3F97D92",
  "hideSSID": "1",
  "SSIDStrategy": "2",
  "branch": "A31_stable_4.6",
  "group": "0",
  "wmrm_version": "4.2",
  "internet": "1",
  "MAC": "00:22:6C:1D:AC:52",
  "STA_MAC": "00:22:6C:1D:AC:54",
  "CountryCode": "CN",
  "CountryRegion": "1",
  "netstat": "2",
  "essid": "42542D3235434A4657",
  "apcli0": "deviceIP",
  "eth2": "",
  "ra0": "10.10.10.254",
  "eth_dhcp": "1",
  "VersionUpdate": "0",
  "NewVer": "0",
  "set_dns_enable": "1",
  "mcu_ver": "35",
  "mcu_ver_new": "0",
  "dsp_ver": "0",
  "dsp_ver_new": "0",
  "date": "2023:01:30",
  "time": "15:12:52",
  "tz": "0.0000",
  "dst_enable": "1",
  "region": "unknown",
  "prompt_status": "1",
  "iot_ver": "1.0.0",
  "upnp_version": "1005",
  "cap1": "0x305200",
  "capability": "0x28e90b80",
  "languages": "0x6",
  "streams_all": "0x7bff7ffe",
  "streams": "0x7b9831fe",
  "external": "0x0",
  "plm_support": "0x16",
  "preset_key": "10",
  "spotify_active": "0",
  "lbc_support": "0",
  "privacy_mode": "0",
  "WifiChannel": "11",
  "RSSI": "-31",
  "BSSID": "8C:19:B5:A5:F0:42",
  "battery": "0",
  "battery_percent": "0",
  "securemode": "1",
  "auth": "WPAPSKWPA2PSK",
  "encry": "AES",
  "upnp_uuid": "uuid:FF31F09E-74C5-E074-E359-B693FF31F09E",
  "uart_pass_port": "8899",
  "communication_port": "8819",
  "web_firmware_update_hide": "0",
  "ignore_talkstart": "0",
  "web_login_result": "-1",
  "silenceOTATime": "",
  "ignore_silenceOTATime": "1",
  "new_tunein_preset_and_alarm": "1",
  "iheartradio_new": "1",
  "new_iheart_podcast": "1",
  "tidal_version": "2.0",
  "service_version": "1.0",
  "ETH_MAC": "00:00:00:00:00:00",
  "security": "https/2.0",
  "security_version": "2.0"
}`
My first stab at configuring this device so perhaps I'm missing something, but here's the (very slim) `media_player` config for posterity: 
`- platform: linkplay
  host: deviceIP
  name: XXX
  volume_step: 10
  uuid: 'FF31F09E74C5E074E359B693'
`

**Comment by DanielHouston** [comment]
Same error when playing local media, so looks like it's not explictly a TTS issue. However not seeing the problem when using the radio media type.

**Comment by christi-g** [comment]
I had the same problem. 
i solved it changing form homeassistant.local to the ip adress in my case 192.168.0.20
You can find the option in Settings -> System -> Network and than put your home assistant IP unter Local network

It seems that the speaker can't resolve the adress .local

**Comment by DanielHouston** [comment]
Thanks - moving away from .local has removed the errors in the logs. However the device still seems to not respond when trying to play media.
Strangly though, hitting the HTTP API directly with setPlayerCmd at a publicly available mp3 works:
http://deviceIP/httpapi.asp?command=setPlayerCmd:play:http://ia902203.us.archive.org/11/items/testmp3testfile/mpthreetest.mp3

but even directly calling the HTTP API with a home assistant hosted media URL does not work:
http://deviceIP/httpapi.asp?command=setPlayerCmd:play:http://HAURL.HADOMAIN/api/tts_proxy/f7ff9e8b7bb2e09b70935a5d785e0cc5d9d0abf0_en_-_google_translate.mp3

**Comment by DanielHouston** [comment]
> It seems that the speaker can't resolve the adress .local

it seems, that the device doesn't want to resolve any address I host locally, but you're right: It works with a direct IP address. This seems to be an issue with the S50/S50 Firmware and **not** this custom component

Closing this out but for future historians who find this solution: Setting the HA Installation's local network value to a routeable IP  address only will fix this problem. In my case, I have both a domain and a seperate IP which routes to HA and this works fine.
