### ISSUE TITLE
Detected integration that calls media_source.async_resolve_media without passing an entity_id

### ISSUE THREAD

**Issue by damocles-dev** [nagyrobi/media_player.linkplay#107]
Hi Árkosi,

I use your fantastic linkplay integration for my loved audiopro c5, but today I updated my hass and now the radio browser integration seems unable to play any station.

The logs show this message:
<pre>
2023-02-14 18:01:07.616 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that calls media_source.async_resolve_media without passing an entity_id
. Please report issue for media_source using this method at homeassistant/components/media_source/__init__.py, line 147: report("calls media_source.async_resolve_media 
without passing an entity_id")
</pre>

Can this error be easily fixed?

**Comment by nagyrobi** [comment]
Warning fix in https://github.com/nagyrobi/home-assistant-custom-components-linkplay/commit/c2cdac8b0e9f353be304b7b42156d15da0be8479
