### ISSUE TITLE
Joining multiroom group does not work, if host is a resolvable name 

### ISSUE THREAD

**Issue by akloeckner** [nagyrobi/media_player.linkplay#111]
While testing #110, I noticed this issue. If the master player is set up with a resolvable `host` name, it cannot be joined by slaves through this integration. That is because the respective command requires an IP address and not a name.

So, this would work: `https://192.168.0.13/httpapi.asp?command=ConnectMasterAp:JoinGroupMaster:eth192.168.0.25:wifi0.0.0.0`

While this would not: `https://192.168.0.13/httpapi.asp?command=ConnectMasterAp:JoinGroupMaster:ethSoundSystem_ABCD:wifi0.0.0.0`

I'm not sure how easy it will be to fix that, because not even  `getStatusEx` returns an obvious IP address. There is a field `apcli0` holding the correct IP, but I don't know what it is supposed to represent.

The command is assembled using the `host` here: https://github.com/nagyrobi/home-assistant-custom-components-linkplay/blob/c2cdac8b0e9f353be304b7b42156d15da0be8479/custom_components/linkplay/media_player.py#L2219

**Comment by nagyrobi** [comment]
It's not supported by the player firmware. The firmware api requires IP addresses.

**Comment by akloeckner** [comment]
That's also what my tests suggested. However, we might find a way to replace names with addresses whenever necessary? Just like the `slave_ip` solution. But that would require some more thought.

Or we make sure it's made crystal clear in the documentation. I just read it. Actually it says "IP address". Maybe it will suffice for the moment to add explicitly that names won't work?

https://github.com/nagyrobi/home-assistant-custom-components-linkplay/blob/c2cdac8b0e9f353be304b7b42156d15da0be8479/README.md?plain=1#L60

Update: See #112 for a proposal.
