### ISSUE TITLE
Muting the master of a multi-room group does not seem to work

### ISSUE THREAD

**Issue by akloeckner** [nagyrobi/media_player.linkplay#114]
If I have a group of players in a multi-room group, I cannot mute the master. I can, however, mute any slave. And I can also mute the device, if it is not grouped in multi-room mode.

I wonder, if this the root of the issue:
https://github.com/nagyrobi/home-assistant-custom-components-linkplay/blob/c2cdac8b0e9f353be304b7b42156d15da0be8479/custom_components/linkplay/media_player.py#L1686-L1689

Why would the master need to be muted using a slave command?

If I use the non-slave command manually (by opening `http://wohnzimmer-arylic/httpapi.asp?command=setPlayerCmd:mute:1`) it works as expected.

**Comment by akloeckner** [comment]
I found the commit introducing this piece of code: https://github.com/nagyrobi/home-assistant-custom-components-linkplay/commit/2f748c9704cbd4ff5e73c97a8a2f87fb470b024c , line 562. Maybe it helps getting to grips with it. Unfortunately, I don't see why this was introduced...

**Comment by akloeckner** [comment]
@nagyrobi, while researching another issue, I have found some more pieces of code, that do not make sense (at least to me). Would you support me in reviewing and merging some code improvements? I would then use some of my spare time to polish up this component. This might very well also contain some refactoring, e.g. I have found a few (at least seemingly) redundant multiroom-variables.

**Comment by nagyrobi** [comment]
Until the end of this year, it's very unlikely that I will have any spare time for this.

**Comment by akloeckner** [comment]
Ok, thanks for being so frank! I think, I'll try and fix things on my own fork then, while they occur. We can always start to merge things back. Just let me know.
