### ISSUE TITLE
Unable to use tts 

### ISSUE THREAD

**Issue by nunokaneco** [nagyrobi/media_player.linkplay#119]
Hello 

I'm not able to listening any msg from the TTS, but all the other stream ways are working well including local files and web radio 

I tryed also to create a long frase in order to try avoid the 800ms of silence at the beginning of the stream, but I still no listening any from this stream way 

Can you please help me?

Thank you

**Comment by nagyrobi** [comment]
Try https://github.com/nimroddolev/chime_tts
