### ISSUE TITLE
Rakoit M50 unavailable

### ISSUE THREAD

**Issue by staxza** [nagyrobi/media_player.linkplay#125]
I am trying to add the Rakoit M50 and HA400 but it shows as unavailable

These are running the A97 chipset.

**Comment by staxza** [comment]
I fixed it. It was set to http protocol while the A97 modules are using https

**Comment by SeRG1k17** [comment]
@staxza Hello. Were you able to successfully integrate this device?

**Comment by staxza** [comment]
Yes, got it integrated with control and multi room. The only thing that did not work is TTS.

**Comment by SeRG1k17** [comment]
Thank you. As I understand. It is impossible to get full control like a arylic boards. This may be due to the fact that they have different firmware or chip inside.
I'm interested in the possibility of changing the source from HA as I want. Are you implemented this feature on your project?
@staxza

**Comment by staxza** [comment]
I am able to change sources. I am also testing the HA400 with A97 chipset and can use the aditional master input sources like optical 2 and line-in 2 that is not listed in the integration documentation as yet
