### ISSUE TITLE
Example config doesn't pass checks on 2023.11.2

### ISSUE THREAD

**Issue by psarossy** [nagyrobi/media_player.linkplay#127]
Configuration invalid!

Invalid config for [media_player.linkplay]: [announce_volume_increase] is an invalid option for [media_player.linkplay]. Check: media_player.linkplay->announce_volume_increase. (See ?, line ?).

Commenting out the announce_volume_increase variable makes the config pass

**Comment by nagyrobi** [comment]
Thank you. That option is deprecated. Removed from doc.
