### ISSUE TITLE
Using deprecated constants for supported features

### ISSUE THREAD

**Issue by akloeckner** [nagyrobi/media_player.linkplay#131]
Just upgraded HA to 2024.1 and it asks me to report this log entry here:

Entity None (<class 'custom_components.linkplay.media_player.LinkPlayDevice'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|VOLUME_SET|VOLUME_MUTE|PREVIOUS_TRACK|NEXT_TRACK|PLAY_MEDIA|VOLUME_STEP|SELECT_SOURCE|STOP|PLAY|SHUFFLE_SET|SELECT_SOUND_MODE|BROWSE_MEDIA|REPEAT_SET|GROUPING: 1039933>, please create a bug report at https://github.com/nagyrobi/home-assistant-custom-components-linkplay/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by nagyrobi** [comment]
Update your Linkplay integration to the latest.
