### ISSUE TITLE
Integration problems with Harman Kardon Allure

### ISSUE THREAD

**Issue by javierferwolf** [nagyrobi/media_player.linkplay#132]
Hello everyone, please has someone tried to connect this integration with the A88 v4.0 chips for example with Harman Kardon astra or Allure models?

**Comment by akloeckner** [comment]
I have tried to put the Allure in a sync group with my Arylic master and failed. It seems to be incompatible, if the firmware is below 4.6. That version also added a new http API. (https://forum.arylic.com/t/new-4stream-app-and-firmware-upgrade-4-6-328252)

So, I fear the device will not work with this integration unless flashed with a custom firmware. If you're willing to try that, maybe this forum topic will help: https://forum.arylic.com/t/question-about-non-arylic-product . I'd appreciate if you could update me then, if it does work. 🙏
