### ISSUE TITLE
Updating linkplay media_player took longer than the scheduled update interval

### ISSUE THREAD

**Issue by bboykaos** [nagyrobi/media_player.linkplay#134]
Hello, I've been getting this error for a few days every time I restart Home Assistant, and I'm forced to restart the component to make it work again: 
**Updating linkplay media_player took longer than the scheduled update interval 0:00:03.** 

Is there anything that can be done to eliminate this problem? I have the latest version of HA available to date.

**Comment by nagyrobi** [comment]
Your Home Assistant boots up slower than expected, I guess it's overloaded with various components...
Maybe switch to some faster hardware if you need that many...

**Comment by bboykaos** [comment]
Thank you for the response. I have a Raspberry Pi 4, and the CPU never exceeds 50%, but perhaps i have a slow SD card. Do you think I could solve this by using an SSD?

**Comment by nagyrobi** [comment]
I don't know. It may relate to your network too.
