### ISSUE TITLE
Announcements/TTS: how to use the resume feature?

### ISSUE THREAD

**Issue by akloeckner** [nagyrobi/media_player.linkplay#135]
I'm trying to use TTS announcements to my linkplay devices and I would like the music to resume playing automatically after the announcements. But I cannot get it to work: my music always remains stopped after an announcement.

Could someone please point me in the right direction how to use this feature?

What I tried:
* Test with Spotify and URL sources.
* From the developer UI start the tts.speak and google_translate_say services.

**Comment by nagyrobi** [comment]
I'm sorry I stopped using TTS with HA since more than a year now. I can't help with this.

**Comment by akloeckner** [comment]
Thanks for the feedback. So, I guess something broke in that time. I'll investigate and maybe some user comes up with some helpful experience in the meantime...

**Comment by StefanW86** [comment]
Same here. But i found a workaround or a possible explanation.

If i snapshot the linkplay, play a tts with tts.speak wait x seconds and then do the restore, my music resume.

If i dont wait the time, the music dosnt resume. So i think, there is an issue with the time to wait for the tts to finish.
