### ISSUE TITLE
The integration is not working with 2024.5.0b0

### ISSUE THREAD

**Issue by r11a** [nagyrobi/media_player.linkplay#136]
Getting error when upgrading to version 2024.5.0b0
Rolled back to version 2024.4.3

**Comment by nagyrobi** [comment]
What error?

**Comment by r11a** [comment]
“Can’t start the Linkplay integration”
Only rolling back to version 2024.4.3 solves the issue

unfortunately I don’t have the log.

**Comment by nagyrobi** [comment]
Can't fix without the log.

**Comment by r11a** [comment]
Invalid config
The following integrations and platforms could not be set up:

[linkplay](https://github.com/nagyrobi/home-assistant-custom-components-linkplay) ([Show logs](http://192.168.1.171:8123/config/logs?filter=linkplay))
linkplay.media_player ([Show logs](http://192.168.1.171:8123/config/logs?filter=linkplay.media_player))

LOG FILE:

Logger: homeassistant.setup
Source: setup.py:404
First occurred: 9:26:08 PM (1 occurrences)
Last logged: 9:26:08 PM

Error during setup of component linkplay
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linkplay/__init__.py", line 141, in setup
    hass.services.async_register(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2489, in async_register
    self._hass.verify_event_loop_thread("async_register")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'linkplay' calls async_register from a thread at custom_components/linkplay/__init__.py, line 141: hass.services.async_register(. Please report it to the author of the 'linkplay' custom integration.



Logger: homeassistant.setup
Source: setup.py:481
First occurred: 9:26:08 PM (4 occurrences)
Last logged: 9:26:08 PM

Unable to prepare setup for platform 'linkplay.media_player': Unable to set up component.


Hope it helps 

Thank You!

**Comment by nagyrobi** [comment]
Please try now, by re-installing the `master` version of the custom component through HACS.

**Comment by r11a** [comment]
I can't download any version other then 3.20..
when trying to selrct the master version from the version selector it's returen to 3.20

**Comment by r11a** [comment]
I Have reinstalled the master version via the update service from the developer tool and now there's no error anymore :) 

Thank You very much!

**Comment by garagara93** [comment]
@nagyrobi hi I have a new error with the 3.2.1 version. 
I tried to install the master version also, but it didn't work.


the log says

Failed communicating with LinkPlayDevice (httpapi) 'Soundbar': <class 'aiohttp.client_exceptions.ClientConnectorSSLError'>

thanks for your support
