### ISSUE TITLE
Error with new Home Assistant Core - 2024.7.0

### ISSUE THREAD

**Issue by twofacedsquare** [nagyrobi/media_player.linkplay#145]
Getting the following error after upgrade to Home Assistant Core 2024.7.0

Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:364
integration: Media player (documentation, issues)
First occurred: 1:22:25 PM (2 occurrences)
Last logged: 1:22:25 PM

Error while setting up linkplay platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/linkplay/media_player.py", line 276, in async_setup_platform
    linkplay = LinkPlayDevice(name,
              ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linkplay/media_player.py", line 314, in __init__
    self._factory = UpnpFactory(requester, disable_unknown_out_argument_error=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UpnpFactory.__init__() got an unexpected keyword argument 'disable_unknown_out_argument_error'

Rolling back to 2024.6.4 resolves the issue

**Comment by twofacedsquare** [comment]
Making the following change to  /config/custom_components/linkplay/media_player.py fixes this

![image](https://github.com/nagyrobi/home-assistant-custom-components-linkplay/assets/26843110/9bb8828c-2654-45d5-a7a7-380bd423b852)

**Comment by NicoLouis-be** [comment]
same issue for me
suggested solution solved it for me and it's back working

**Comment by nagyrobi** [comment]
Fixed in https://github.com/nagyrobi/home-assistant-custom-components-linkplay/commit/e1d74c353c71b82b913d3b3f99440ec4daf37837
