### ISSUE TITLE
Input source wifi

### ISSUE THREAD

**Issue by m1nka** [nagyrobi/media_player.linkplay#53]
Hi,
for me the input source wifi does not work/exist. My hardware is an ***Arylic Up2Stream Mini v3***. According to [their docs](https://developer.arylic.com/httpapi/#select-input-source) wifi should be supported as input source (they also [mention at the top](https://developer.arylic.com/httpapi/#http-api) that they are using standard Linkplay API). 

This is my `configuration.yaml`:

```
media_player:
    - platform: linkplay
      host: 192.168.0.181
      name: Wohnzimmer
      volume_step: 10
      icecast_metadata: 'StationNameSongTitle'
      multiroom_wifidirect: False
      sources: 
        {
          'bluetooth': 'Bluetooth',
          'wifi': 'Wifi'
        }
```

Wifi is kinda the most important input source since it plays all kinds of sources like Spotify, Airplay, Amazon Music etc. Would be fantastic if I could get this to work. See screenshot below where wifi input source is missing.

Thx a lot. 

<img width="394" alt="Screenshot 2021-11-15 at 21 47 39" src="https://user-images.githubusercontent.com/6085453/141851787-7bd22201-a5a6-4017-9542-e7c6507729cd.png">

**Comment by nagyrobi** [comment]
WiFi input source is virtual. It's not shown in that dropdown list because inside WiFi there is already the "Spotify, Airplay, Amazon Music".

**Comment by BCsabaEngine** [comment]
Same issue. WiFi virtual connection must be set with other integration, ex: spotify (and there you can setup playlist). Robi's integration "just" show the status.
