### ISSUE TITLE
Question: How do I update firmware? 

### ISSUE THREAD

**Issue by Yersi88** [nagyrobi/media_player.linkplay#62]
Hello, 

Sorry for opening an issue here, but I didn't know where to ask. How do I update the firmware on my devices? I can't seem to find the option in the app. 

Any help much appreciated :)

**Comment by nagyrobi** [comment]
The factory app (4Stream) will show you with a little arrow icon pointing upwards, if there's a firmware update for that specific device.

**Comment by Yersi88** [comment]
> The factory app (4Stream) will show you with a little arrow icon pointing upwards, if there's a firmware update for that specific device.

A month ago when I bought them, there was an update available but it failed, and since then I can't seem to get it to update. Fw version still same as when I bought them.

**Comment by nagyrobi** [comment]
There's nothing you can do I'm afraid.
