### ISSUE TITLE
Help: Problems with sync between devices. 

### ISSUE THREAD

**Issue by Yersi88** [nagyrobi/media_player.linkplay#63]
Hello, 

I have 3 linkplay devices: 
2x https://www.amazon.co.uk/dp/B084R8N8KD/ 
1x https://www.aliexpress.com/item/1005002087732418.html 

The two Arylic devices can link successfully and play music in sync (when wifidirect is disabled). However, when I try to link the other one (linkplay board) nothing really happens, the integration indicates they are linked but nothing is playing from it. App doesn't acknowledge the link as well. 

I tried the option: `multiroom_wifidirect: True` 
But when this is enabled, nothing will sync. If I try to sync any device the sync fails with audio prompt: "Failed to connect to network" from the device that is trying to sync to master. Arylic won't sync to each other or to linkplay board. 

Any suggestions? 

Many thanks!

**Comment by nagyrobi** [comment]
If you enable wifi direct mode, you have to be 100% sure the devices are quite close to each other with no obstacles as they connect directly with own AP mode etc.

With no wifi direct, they should connect via their existing network connection, as long as their firmwares are compatible with each other.

What are your firmware versions?

**Comment by Yersi88** [comment]
Yeah they are really close to each other so connection should not be a problem. Even tried  putting them next to each other. 

Firmware for Arylic: 4.6.337862.29 (both same) 
Firmware for Linkplay board: 4.2.8715.10

**Comment by nagyrobi** [comment]
I have 3 Arylic devices + 1 Audiocast and multiroom works just fine. Arylics connect wired, Audiocast is WiFi.

Did you try to link from the app?
What app do you use?

**Comment by Yersi88** [comment]
Yeah the Arylic ones are quite trouble free, it's the board that doesn't want to sync. 

I use 4Stream but I tried the other ones too without much success. 
App will fail to link the board as well. 

I thought that maybe the board has outdated firmware because it's older than the Arylic. But app doesn't seem to want to push updates. 

I tried to update the board with api call found here: https://github.com/AndersFluur/LinkPlayApi/blob/master/api.md 
But this call: http://192.168.100.230/httpapi.asp?command=getMvRemoteUpdateStatus returns "22" which is supposed to mean: "Downloading the update file failed". Not sure why that might be the case.

**Comment by nagyrobi** [comment]
I think you should use a different board.

Maybe also ask here: https://forum.arylic.com/

**Comment by Yersi88** [comment]
Yeah perhaps, But I'm kind of surprised that the wifidirect mode just doesn't work at all. On any of the devices I have. Does it work for you?

**Comment by nagyrobi** [comment]
When I had them on my workbench it used to work but can't test anymore as they are in distant locations installed. Several firmware updates since.

**Comment by nagyrobi** [comment]
Seems others have issue too:
https://forum.arylic.com/t/firmware-upgrade-4-6-337862/1342/43

It's firmware related.

**Comment by Yersi88** [comment]
So I tried to install the app on ipad. And that one doesn't even attempt to link the board to arylic. It just says that firmware is out of date.
