### ISSUE TITLE
Linkplay shows title when pressing start but after 2 seconds it stops

### ISSUE THREAD

**Issue by tunguskar** [nagyrobi/media_player.linkplay#66]
Hi There, 

I have a strange problem with link player. Configuration is like this:

`media_player:
  - platform: linkplay
    host: xxx.xxx.xxx.xxx
    name: Sound WZ
    icecast_metadata: "StationNameSongTitle"
    sources:
      {
        'https://ice2.somafm.com/folkfwd-128-mp3': 'Soma Folk Forward',
        "https://ice4.somafm.com/indiepop-128-aac": "Soma Alternative",
        "http://wdr-1live-live.icecast.wdr.de/wdr/1live/live/mp3/128/stream.mp3": "Eins Live",
      }
`

Visualization and handling is over mini media player. 

The problem is, that when I want to start the soma lifestream it shows the current title for about 2-3 seconds and then stops again. With The third source (Eins Live) it works fine. I turned already the log on but but there is no entry about this topic. 

Does anyone has the same problem?

**Comment by nagyrobi** [comment]
Please use http, not http**s** URLs. Linkplay chipsets have limited supporrt for https. 

Using https is useless in practice anyway for a webradio stream, also a waste of computig resources for this kind of usage.

**Comment by tunguskar** [comment]
Thanks for the fast reply @nagyrobi
