### ISSUE TITLE
unavailable devices

### ISSUE THREAD

**Issue by r11a** [nagyrobi/media_player.linkplay#70]
Hi,

Since the last update  3.0.3 the devices allways become unavailable for few seconds 

This error originated from a custom integration.

Logger: custom_components.linkplay.media_player
Source: custom_components/linkplay/media_player.py:383
Integration: Linkplay (documentation, issues)
First occurred: 12:43:56 (15 occurrences)
Last logged: 12:53:34

Failed communicating with LinkPlayDevice 'Bathroom': <class 'asyncio.exceptions.TimeoutError'>
Failed communicating with LinkPlayDevice 'Bedroom': <class 'asyncio.exceptions.TimeoutError'>

**Comment by nagyrobi** [comment]
Your network seems weak - the devices seem loose connection often and when HA tries to reconnect, it runs on timeout, which is 2 seconds.

A good network has a latency of a few miliseconds, should fit largely in 2 seconds.

I implemented this on purpose - to bring attention to weak networks problem.

**Comment by r11a** [comment]
@nagyrobi There's any option to avoid it?

Thanks

**Comment by nagyrobi** [comment]
I think the best approach would be to fix your network. Use cabled Ethernet, or for WiFi use more APs with lower power, to increase coverage properly.

In `media_player.py` try increasing the value of `API_TIMEOUT`. You will likely see other warnings, generated by HA asyncio though.

How often do you experience this?

**Comment by r11a** [comment]
Hi,
The devices are connected to my Wi-Fi and I’m getting great signal when I’m monitoring the Ubiquity AP via the ubiquity controller. I don’t think that there’s any WI-FI issue in the previous version the devices always was available and I used them a lot. 

It become unavailable every few minutes for one or two minutes. 
I’m not sure what value should I suppose to increase. 
thank you again for your kind support :)

**Comment by nagyrobi** [comment]
> previous version the devices always was available

The truth is that the devices were shown as available errorneously by HA. That was not corresponding to reality.

Try increasing the api timeout to 10, 20, 30, etc seconds until the problem disappears for you. Restart HA each time after you modify the file. But this is not the real fix to your problem.

I also use UniFi, I'll do some more checks too. But I have no problems at all.

**Comment by r11a** [comment]
For the last few hours ther's no disconnecting anymore.
I'll update you tommorow 
Thank You

**Comment by nagyrobi** [comment]
See? It's very likely a WiFi network coverage or interference problem, you've also had before, you just didn't notice because there was no warning.

Unifi dashboard doesn't show short dropouts.

**Comment by r11a** [comment]
From yesterday it is stable, I do not know what has changed ... no complaints :)

**Comment by nagyrobi** [comment]
Maybe [ask](https://github.com/SpacehuhnTech/esp8266_deauther) your neighbors... :)

**Comment by r11a** [comment]
:) I will 

Thanks!
