### ISSUE TITLE
Link_play creating new entities 

### ISSUE THREAD

**Issue by etxttul** [nagyrobi/media_player.linkplay#71]
Hi,

Once again, nothing works, yet again I find that there are new entities created without me touching the system, more than doing normal HA releases and possibly Link_play upgrades. The reason is that new entities has been created, media_player.stereon, referred to in scripts lovelace and automations has been changed to media_player.stereon_1 then media_player.stereon_2, then media_player.stereon_3. Firstly can this behavior be stopped in the future, Secondly is there a smart way to get it back to working state without changing everything referring to the first entity. It is quite a job and quite annoying.

BR
Tobe

**Comment by nagyrobi** [comment]
It has been written in the release notes of v3 that upgrading from v2 is a breaking change related to this.

And it was also written how to fix it easily.

Also there's a new option `uuid` you should set it's written too in the readme doc.

This behavior can be stopped if you pay attention to upgrade notices and read them and do what's witten there. Don't just go click upgrading without reading first - do your homework.

You can of course reinstall back the v2 version at any time if you don't like the new.
