### ISSUE TITLE
Support for Wiim mini casting device?

### ISSUE THREAD

**Issue by spernesen** [nagyrobi/media_player.linkplay#72]
Hello, 

I just bought some Wiim mini cast devices (link: https://wiimhome.com/Overview.html). These devices are developed by Linkplay technology, but when I try to add them into HA with this integration, I immediately notice that they are unavailable.

From HA logg: 

2022-04-26 23:07:41 WARNING (MainThread) [custom_components.linkplay.media_player] Failed communicating with LinkPlayDevice (httpapi) 'spisestue': <class 'aiohttp.client_exceptions.ClientConnectorError'>

Is it possible to add function for these devices? Or is this something completely different?

Best regards,

**Comment by nagyrobi** [comment]
Please post what response do you get from the devices when accessing the httpapi:

```
http://spe.ak.er.ip/httpapi.asp?command=getStatusEx
http://spe.ak.er.ip/httpapi.asp?command=getPlayerStatus
```

**Comment by spernesen** [comment]
Thx for fast reply. 
Hmm, same error on both devices for both links:

«ERR_CONNECTION_FAILED»

Best regards,

**Comment by nagyrobi** [comment]
It means those devices are not based on a module supported by this integration.

**Comment by danielbheyl** [comment]
@nagyrobi These players require https.  Here are the results:

https://player.ip/httpapi.asp?command=getStatusEx

{ "language": "en_us", "ssid": "WiiM Pro-9D18", "hideSSID": "0", "firmware": "Linkplay.4.8.503558", "build": "release", "project": "WiiM_Pro_with_gc4a", "priv_prj": "WiiM_Pro_with_gc4a", "project_build_name": "WiiM_Pro_with_gc4a", "Release": "20230104", "FW_Release_version": "", "cast_enable": 1, "cast_usage_report": 1, "group": "0", "wmrm_version": "4.2", "expired": "0", "internet": "1", "uuid": "FF98F09C7B752227DC39DAB4", "MAC": "B8:13:32:D5:9D:18", "BTMAC": "b8:13:32:d5:9d:19", "InitialConfiguration": "1", "AP_MAC": "BA:13:32:D5:9D:18", "date": "2023:01:14", "time": "13:18:20", "netstat": "2", "essid": "4865796C", "apcli0": "192.168.1.138", "eth0": "0.0.0.0", "eth2": "0.0.0.0", "ETH_MAC": "00:00:00:00:00:00", "hardware": "AmlogicA113", "VersionUpdate": "0", "NewVer": "0", "mcu_ver": "0", "mcu_ver_new": "0", "update_check_count": "4", "ra0": "10.10.10.254", "temp_uuid": "6B1462687F55572F", "cap1": "0x40000400", "capability": "0x20084800", "languages": "0x1ec", "alexa_ver": "20180604", "alexa_beta_enable": "0", "alexa_force_beta_cfg": "0", "dsp_ver": "", "ModuleColor": "0", "dsp_ver_new": "", "uboot_verinfo": "", "kernel_verinfo": "#19 SMP PREEMPT Tue Dec 6 19:05:57 CST 2022", "silence_ota_flag": "1", "ota_interface_ver": "2.0", "streams_all": "0x1eff33fd", "streams": "0x1eff33fd", "region": "unknown", "volume_control": "1", "external": "0x0", "preset_key": "12", "plm_support": "0x700016", "lbc_support": "0", "WifiChannel": "0", "RSSI": "-32", "BSSID": "90:09:D0:1E:EB:63", "wlanSnr": "35", "wlanNoise": "-92", "wlanFreq": "5200", "wlanDataRate": "433", "battery": "0", "battery_percent": "0", "securemode": "1", "upnp_version": "1005", "upnp_uuid": "uuid:FF98F09C-7B75-2227-DC39-DAB4FF98F09C", "uart_pass_port": "8899", "communication_port": "8819", "web_firmware_update_hide": "0", "new_tunein_preset_and_alarm": "1", "new_iheart_podcast": "1", "tidal_version": "2.0", "service_version": "1.0", "HiFiSRC_version": "1.0", "EQ_support": "Eq10HP_ver_1.0", "audio_channel_config": "1.0", "power_mode": "-1", "security": "https\/2.0", "security_version": "3.0", "security_capabilities": { "ver": "1.0", "aes_ver": "1.0" }, "public_https_version": "1.0", "privacy_mode": "0", "DeviceName": "Stereo", "GroupName": "Stereo" }

https://player.ip/httpapi.asp?command=getPlayerStatus

{"type":"0","ch":"0","mode":"10","loop":"0","eq":"0","status":"play","curpos":"-31562","offset_pts":"-31562","totlen":"151000","Title":"556E73746F707061626C65","Artist":"546865205069616E6F2047757973","Album":"496E737472756D656E74616C204C6F766520536F6E6773","Vendor":"unknown","alarmflag":"0","plicount":"44","plicurr":"5","vol":"100","mute":"0"}

Can we integrate these using https?
