### ISSUE TITLE
Is it able to call an action to play a playlist on Linkplay device?

### ISSUE THREAD

**Issue by dinhchinh82** [nagyrobi/media_player.linkplay#76]
I've installed this linkplay component and it works great.

By the way, I have not found the linkplay action of this component to play a playlist from local storage instead of selecting only 1 media file as current. 

Is there a solution to support playing a playlist on Home assisstant action from Script/Automation?

Thank you.

**Comment by nagyrobi** [comment]
What do you mean by _local storage_?

**Comment by dinhchinh82** [comment]
> What do you mean by _local storage_?

I mean the local media files which are uploaded to the same storage with Home Assistant server or the media files on the same Local network with the Home Assistant instance.

**Comment by nagyrobi** [comment]
For that kind of playlists you need to use [Music Assistant](https://github.com/music-assistant/hass-music-assistant) which is currently a Custom Component, still under development, but afaik will be included officially in Home Assistant when finished.

This component has preliminary (beta) support for Music Assistant natively with metadata and previous/next controls to navigate within a playlist. You will be able to use service calls of Music Assistant to select playlists, targetting any supported media player.

**Comment by dinhchinh82** [comment]
@nagyrobi great !!. Thank you for your suggestion.
