### ISSUE TITLE
Missing config flow...unable to load custom component

### ISSUE THREAD

**Issue by joseffallman** [nagyrobi/media_player.linkplay#77]
Hi
I getting this error in the logg. I think i may have seen it before but from Home Assistant 2022.5.5 i'm unable to load the integration. 
It's strange since the manifest.json declare config_flow to false.

Logger: homeassistant.config_entries
Source: config_entries.py:316
First occurred: 21:10:30 (1 occurrences)
Last logged: 21:10:30

Error importing platform config_flow from integration linkplay to set up linkplay configuration entry: No module named 'custom_components.linkplay.config_flow'

**Comment by nagyrobi** [comment]
I'm also on  2022.5.5, and also on 2022.6 betas... Never seen that error...

Sorry this integration doesn't support any config_flow, it has to be configured manually via YAML.

There must be some local issue you have, You should try to completely remove all configs and remove custom component too (delete all linkplay folder). 
Restart HA.
Reinstall custom component.
Restart HA.
Add YAML config.
Restart HA.
