### ISSUE TITLE
Media player wont states

### ISSUE THREAD

**Issue by nasrulll** [nagyrobi/media_player.linkplay#79]
Hello Dev..
first thanks so much for the code.. i have been using it for so long.
i would like to report that i face a condition where i need to restart HA to make media player on a state condition
and it wont last long then media player in a off condition. i use 3 Arylic up2stream.
i have checked few variable like ip address, HA media player configuration, all good thought.

thanks

**Comment by nagyrobi** [comment]
Please look in homeassistant.log, what error message do you see.

**Comment by nasrulll** [comment]
Hi @nagyrobi , sorry for being late to reply. i would like to clarify that there is no problem with the code. the issue was DHCP. i have to set lease time in mikrotik and sync it with DHCP server addon to make it run well. thank you so much for the code and respond
