### ISSUE TITLE
Arylic Up2Stream HD Dac state unavailable

### ISSUE THREAD

**Issue by Kamstrup1992** [nagyrobi/media_player.linkplay#82]
I have several Arylic devices in my house with no problem, i have recently bought an Arylic up2stream HD Dac, also with Linkplay. State is always unavailabe in HA. 
I get the following error in HA log:
2022-07-04 23:31:41 WARNING (MainThread) [custom_components.linkplay.media_player] Failed communicating with LinkPlayDevice (start) '192.168.1.216': uuid: FF970023601DD7574229E08A <class 'aiohttp.client_exceptions.ClientConnectorError'>

**Comment by onlyoneme** [comment]
Similar issue with Linkplay based WiiM Mini.

**Comment by onlyoneme** [comment]
Both devices are Linkplay based but they are not on A31. I guess the component connects only to A31 items.

**Comment by Kamstrup1992** [comment]
Yeah i figured it was something like that. But perhaps it can be fixed?

**Comment by nagyrobi** [comment]
This component is only able to talk to A31 API. Other chipsets are not supported.
