### ISSUE TITLE
Coverart stopped working for all radio streams.

### ISSUE THREAD

**Issue by craggyh** [nagyrobi/media_player.linkplay#86]
Any idea why lastfm coverart would stop working some time after a recent linkplay component update when they used to work fine for most of my radio stations? Nothing else changed in the config, stream URLs are also unchanged.
I tried a new lastfm API key but didn’t help.

Has something changed in the component that might cause this?

Also, how do I get logs of the icecast/lastfm lookups? I set the linkplay component to debug but don’t see anything in the logs.

**Comment by nagyrobi** [comment]
LastFM employs rate limits for queries, I assume this has been set to more servere lately.

**Comment by craggyh** [comment]
Oh, that thought had crossed my mind at one point if it was something external like a rate limit.

Is there somewhere in the logs I can check if this is the case?

**Comment by nagyrobi** [comment]
Not possible, as LastFM doesn't show that. Sometimes it responds just like the album art cover wouldn't exist in the database. Sometimes it returns a "sheriff star" icon which I filtered out in the code not to show it as it looks dull.

**Comment by craggyh** [comment]
It's possible it's a rate limiting issue but I would have expected it to work at least every once in a while.

Could there be something else going on locally that's stopping it from working? I thought maybe something like upnp not working correctly as I read somewhere that the linkplay component uses http for control but upnp for metadata queries and coverart.

I set my logger to debug for upnp and ssdp but don't see anything in the logs relating to metadata queries or similar. Is there something specific I should be looking for in the logs to make sure the component is definitely trying to query the linkplay speakers for coverart related data?

**Comment by nagyrobi** [comment]
It depends on what you want to play. It only uses UPNP for Spotify and media played from Linkplay phone app.

**Comment by nagyrobi** [comment]
what version of the component do you use?

**Comment by craggyh** [comment]
The component is on version 3.1.5

If UPNP is for spotify then that works because I get coverart in the media
player card. Just nothing for http radio streams even though they used to
work.

**Comment by nagyrobi** [comment]
Just tested, works fine here. You must have some other issue, unrelated to this component like being banned/ratelimited by lastfm, network access to their api, etc.
