### ISSUE TITLE
Where to put "- service: linkplay.join"?

### ISSUE THREAD

**Issue by kylepyke** [nagyrobi/media_player.linkplay#92]
Apologies for the noob questions, but it's unclear from the docs, where in config.yaml I should put:

`  - service: linkplay.join
    data:
        entity_id: media_player.kitchen
        master: media_player.console_player`

Does this need to be defined under `media_player:`, or under `- platform: linkplay`? I seem to get an invalid config no matter where I put it...

Thanks!

**Comment by nagyrobi** [comment]
What do you want to achieve?
