### ISSUE TITLE
hacs.json issue conflicts with fork

### ISSUE THREAD

**Issue by saltinesurfer** [nagyrobi/media_player.linkplay#95]
Hi @nagyrobi , I'm unable to add your plugin to HACS as a custom repository using the github URL as it says it already exists in the HACS store - Would you be able to change the name in the hacs json file in the root so it's different to the integration this was forked from? I have a feeling this will fix it. Cheers!

**Comment by nagyrobi** [comment]
Why would you want to add it as a custom repository? Just install it directly from HACS, as everybody.

**Comment by saltinesurfer** [comment]
Apologies I got mixed up! Ignore me :)
