### ISSUE TITLE
Linkplay won't play audio files locally in HA

### ISSUE THREAD

**Issue by FauxHobo** [nagyrobi/media_player.linkplay#96]
With the addon installed, I have a Tibo Chorus Tap speaker (confirmed supported) that does connect, and confirm works as the speaker confirms when I change source (from BT to WiFi mode) however when I play a file storedd locally on the home assistant I get an error. 

`Logger: aiohttp.server Source: /usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py:405 First occurred: 17:20:43 (3 occurrences) Last logged: 17:21:45
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"`

My HA uses HTTPS via DuckDNS to connect. Knowing Linkplay like HTTPS and prefers HTTP, i'm not sure why it's trying to call out to play this file.

**Comment by nagyrobi** [comment]
Https is not supported by this component.
