### ISSUE TITLE
linkplay.media_player class 'asyncio.exceptions.TimeoutError'>

### ISSUE THREAD

**Issue by RosensRauk** [nagyrobi/media_player.linkplay#97]
This happens alot and every time after reboo/reload.
The speakers work as they should so just irritating with this warning.

Logger: custom_components.linkplay.media_player
Source: custom_components/linkplay/media_player.py:469
Integration: Linkplay (documentation, issues)
First occurred: 11:35:06 (2004 occurrences)
Last logged: 11:35:06

Failed communicating with LinkPlayDevice (httpapi) 'orange': <class 'asyncio.exceptions.TimeoutError'>
Failed communicating with LinkPlayDevice (httpapi) 'lemon': <class 'asyncio.exceptions.TimeoutError'>

**Comment by nagyrobi** [comment]
A Timeout error means nothing else than that linkplay device doesn't answer back to HA within the timeframe needed. Usually it's a sign of a flaky network, which gets heavy traffic when this happens. Perhaps there's something else generating the load while rebooting or reloading.
What are you running Home Assistant server on?

**Comment by RosensRauk** [comment]
Raspberry pi 4 4Gb.
Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.3
Frontend-version: 20221010.0 - latest

Thank you for your answer. As a result I tried de-activating peripherals (BT, jellyfin etc) and sadly to no avail.
My speakers are Audio Pro A10. The API does not have a activate/on command. So after some time the speakers go into powersave mode. Do you think this could be the reason?

**Comment by nagyrobi** [comment]
Oh yes. This integration only supports devices which are always connected to the network.

**Comment by RosensRauk** [comment]
Raspberry pi 4 4Gb.
Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.3
Frontend-version: 20221010.0 - latest

Thank you for your answer. As a result I tried de-activating peripherals (BT, jellyfin etc) and sadly to no avail.
My speakers are Audio Pro A10. The API does not have a activate/on command. So after some time the speakers go into powersave mode. Do you think this could be the reason?
