### ISSUE TITLE
Log is flooded when cast speaker is powered off

### ISSUE THREAD

**Issue by febalci** [nagyrobi/media_player.linkplay#99]
First, thanks for the great integration,

I have “Linkplay based speakers and devices” HACS integration for only purpose to play spotify on my cast speaker. This speaker is connected to a ZWave switch. Whenever i am not at home i switch off this ZWave switch, so the cast speaker is off. But then the HA log is flooded with these every **20** seconds:

` 2022-11-05 02:24:26.010 WARNING (MainThread) [homeassistant.components.media_player] Updating linkplay media_player took longer than the scheduled update interval 0:00:03` 

` 2022-11-05 02:24:26.084 WARNING (MainThread) [custom_components.linkplay.media_player] Failed communicating with LinkPlayDevice (httpapi) 'Marshall_cast': <class 'aiohttp.client_exceptions.ClientConnectorError'> `

Is there a way to enable/disable this integration or some other way so that the log is not flooded and keep HA busy? Thanks…

**Comment by nagyrobi** [comment]
The integration needs the device to always be turned on.
